import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import "./globals.scss";
import Navbar from "../components/Navbar/Navbar";
import {useEffect} from "react";
import {usePathname} from "next/navigation";

const roboto = Roboto({weight: ["300"], subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport = {
    width: 1,
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={roboto.className}>

        <div
            className="text-black dark:text-white flex flex-row justify-center w-full h-full bg-gradient-to-bl from-white to-[#fff] dark:from-black dark:to-[#0d131f] min-h-screen">
            <Navbar />
            <div className="w-[80%] md:w-[45rem]">
                {children}
            </div>
        </div>
        </body>
        </html>
    );
}
